services:
  server_db:
    env_file: ".env"
    image: mongo
    restart: always
    container_name: todovea_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db

  server_app:
    build: ./back
    env_file: "./back/.env"
    restart: always
    container_name: todovea_server_app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - server_db

  front_app:
    build: ./front
    env_file: "./front/.env"
    restart: always
    container_name: todovea_front_app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - server_app

volumes:
  mongodata:
    driver: local
