services:
  server_db:
    env_file: ".env"
    image: mongo
    restart: always
    container_name: todovea_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    expose:
      - "27017"

  server_app:
    build: ./back
    env_file: "./back/.env"
    restart: always
    container_name: todovea_server_app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - server_db
